///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsFontsFreeNetSweet = 'assets/fonts/FontsFree-Net-sweet.ttf';
  static const String fontsYummyFoodiesDemoRegular = 'assets/fonts/YummyFoodies-demo-Regular.ttf';
  static const String imagesBG1 = 'assets/Images/BG 1.png';
  static const String imagesFastFood = 'assets/Images/fastFood.jpg';
  static const String imagesOrganic = 'assets/Images/organic.jpg';

}
